windowrule {
  name = one-password
  float = on
  center = on
  match:class = ^(1password)$
}

windowrule {
  name = one-password-main
  size = 1000 800
  match:class = ^(1password)$
  match:title = — 1Password$
}
