windowrule {
  name = steam
  no_blur = 1
  float = on
  idle_inhibit = fullscreen
  match:class = steam
}

windowrule {
  name = steam-main
  center = on
  size = 2000 1400
  match:class = steam
  match:title = Steam
}

windowrule {
  name = steam-friends
  size = 460 800
  match:class = steam
  match:title = Friends List
}

windowrule {
  name = steam-settings
  decorate = 0
  no_shadow = 1
  border_size = 1
  match:class = steam
  match:initial_title = Steam Settings
}

windowrule {
  name = steam-other
  float = on
  match:class = steam_app_default
}

windowrule {
  name = steam-other-again
  center = on
  match:class = steam_app_default
  match:title = Steam
}
